# -*- mode: ruby -*-
# vi: set ft=ruby :
NonRootUser = 'operador'

$newUser = <<-SCRIPT
#!/bin/bash

# Create operador user
echo "Create user #{NonRootUser}"
useradd -s /bin/bash -m -G sudo -U #{NonRootUser}
SCRIPT

$passwordlessSudo = <<-SCRIPT
#!/bin/bash

echo "#{NonRootUser}    ALL=(ALL) NOPASSWD:ALL" >> "/etc/sudoers.d/#{NonRootUser}"
SCRIPT

$accessUsingSSHkey = <<-SCRIPT
#!/bin/bash

sudo su #{NonRootUser}
sudo mkdir -p /home/#{NonRootUser}/.ssh/
cat /tmp/tmp_id_rsa.pub >> /home/#{NonRootUser}/.ssh/authorized_keys
SCRIPT

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.

  NodeCount = 3
  
  (1..NodeCount).each do |i|
    config.vm.define "k3s-#{i}" do |node|
      
      # Provider configuration
      node.vm.provider :virtualbox do |v|
        v.name    = "k3s-#{i}"
        v.memory  = 2048
        v.cpus    = 1
      end

      # Base configuration
      node.vm.box               = "ubuntu/focal64"
      node.vm.box_version       = "20210803.0.0"
      node.vm.box_check_update  = false
      
      node.vm.hostname          = "k3s-#{i}.192.168.1.#{100+i}.nip.io"

      # Public network configuration
      node.vm.network "public_network", ip: "192.168.1.#{100+i}", bridge: 'wlp3s0'

      # Disable sync folder
      node.vm.synced_folder ".", "/vagrant", disabled: true
      
      # Plugin vagrant-vbguest configuration
      node.vbguest.auto_update  = false

      # Create non-root user
      node.vm.provision "shell", inline: $newUser
      
      # Passwordless sudo for non-root user
      node.vm.provision "shell", inline: $passwordlessSudo
      
      # Passwordless SSH access for operador
      node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/tmp_id_rsa.pub"
      node.vm.provision "shell", inline: $accessUsingSSHkey
    end
  end
end
